<?php defined('SYSPATH') or die('No direct access allowed.');
/*
| -------------------------------------------------------------------
| MIME TYPES
| -------------------------------------------------------------------
| This file contains an array of mime types.  It is used by the
| Upload class to help identify allowed file types.
*/

$mimes = array
(
	'ai'    => array('application/postscript'),
	'aif'   => array('audio/x-aiff'),
	'aifc'  => array('audio/x-aiff'),
	'aiff'  => array('audio/x-aiff'),
	'avi'   => array('video/x-msvideo'),
	'bin'   => array('application/macbinary'),
	'bmp'   => array('image/bmp'),
	'dms'   => array('application/octet-stream'),
	'cpt'   => array('application/mac-compactpro'),
	'class' => array('application/octet-stream'),
	'css'   => array('text/css'),
	'csv'   => array('text/x-comma-separated-values', 'application/vnd.ms-excel'),
	'dir'   => array('application/x-director'),
	'dcr'   => array('application/x-director'),
	'doc'   => array('application/msword'),
	'dvi'   => array('application/x-dvi'),
	'dxr'   => array('application/x-director'),
	'dll'   => array('application/octet-stream'),
	'eml'   => array('message/rfc822'),
	'exe'   => array('application/octet-stream'),
	'eps'   => array('application/postscript'),
	'gif'   => array('image/gif'),
	'gtar'  => array('application/x-gtar'),
	'gz'    => array('application/x-gzip'),
	'htm'   => array('text/html'),
	'html'  => array('text/html'),
	'hqx'   => array('application/mac-binhex40'),
	'jpeg'  => array('image/jpeg', 'image/pjpeg'),
	'jpg'   => array('image/jpeg', 'image/pjpeg'),
	'jpe'   => array('image/jpeg', 'image/pjpeg'),
	'js'    => array('application/x-javascript'),
	'lha'   => array('application/octet-stream'),
	'log'   => array('text/plain', 'text/x-log'),
	'lzh'   => array('application/octet-stream'),
	'midi'  => array('audio/midi'),
	'mid'   => array('audio/midi'),
	'mif'   => array('application/vnd.mif'),
	'mp2'   => array('audio/mpeg'),
	'mp3'   => array('audio/mpeg'),
	'mov'   => array('video/quicktime'),
	'movie' => array('video/x-sgi-movie'),
	'mpe'   => array('video/mpeg'),
	'mpeg'  => array('video/mpeg'),
	'mpg'   => array('video/mpeg'),
	'mpga'  => array('audio/mpeg'),
	'oda'   => array('application/oda'),
	'pdf'   => array('application/pdf', 'application/x-download'),
	'php'   => array('application/x-httpd-php'),
	'php3'  => array('application/x-httpd-php'),
	'php4'  => array('application/x-httpd-php'),
	'phps'  => array('application/x-httpd-php-source'),
	'phtml' => array('application/x-httpd-php'),
	'png'   => array('image/png', 'image/x-png'),
	'ppt'   => array('application/powerpoint'),
	'ps'    => array('application/postscript'),
	'psd'   => array('application/x-photoshop'),
	'qt'    => array('video/quicktime'),
	'ra'    => array('audio/x-realaudio'),
	'ram'   => array('audio/x-pn-realaudio'),
	'rm'    => array('audio/x-pn-realaudio'),
	'rpm'   => array('audio/x-pn-realaudio-plugin'),
	'rtf'   => array('text/rtf'),
	'rtx'   => array('text/richtext'),
	'rv'    => array('video/vnd.rn-realvideo'),
	'sea'   => array('application/octet-stream'),
	'shtml' => array('text/html'),
	'sit'   => array('application/x-stuffit'),
	'smi'   => array('application/smil'),
	'smil'  => array('application/smil'),
	'so'    => array('application/octet-stream'),
	'swf'   => array('application/x-shockwave-flash'),
	'tar'   => array('application/x-tar'),
	'text'  => array('text/plain'),
	'tif'   => array('image/tiff'),
	'tiff'  => array('image/tiff'),
	'tgz'   => array('application/x-tar'),
	'txt'   => array('text/plain'),
	'wav'   => array('audio/x-wav'),
	'wbxml' => array('application/wbxml'),
	'wmlc'  => array('application/wmlc'),
	'word'  => array('application/msword', 'application/octet-stream'),
	'xhtml' => array('application/xhtml+xml'),
	'xht'   => array('application/xhtml+xml'),
	'xl'    => array('application/excel'),
	'xls'   => array('application/excel', 'application/vnd.ms-excel'),
	'xml'   => array('text/xml'),
	'xsl'   => array('text/xml'),
	'zip'   => array('application/x-zip', 'application/zip', 'application/x-zip-compressed')
);